### ISSUE TITLE
*Пожелание. При запуске окно открывается в оконном режиме

### ISSUE THREAD

**Issue by ivan12205** [Kolka2/wwms#1]
При запуске окно открывается в оконном режиме. Лично мне хотелось видеть полноэкранный режим, потому что вроде нет никаких веских причин для оконного режима. (Upd. и настройки тоже, а то больно уж неудобно)
Шаги для воспроизведения:
1. Запустить☻
![фыв1](https://github.com/user-attachments/assets/53b98e17-46b3-403c-b54d-98a9c553886e)

**Comment by Kolka2** [comment]
Не баг. Пока сфокусированы на исправлении критических недочётов. Дополнение функционала возможно в будущем.
