### ISSUE TITLE
Закрытие окна настроек, если файл не существует.

### ISSUE THREAD

**Issue by RomanovaKira** [Kolka2/wwms#10]
При открытии настроек нажимаем кнопку сохранить с ошибочным файлом (почему-то по умолчанию стоит ошибочный файл), после чего у нас закрывается окно настроек, для пользователя это будет неудобно т.к он мог выбрать ошибочный файл, но настройки ему нужны эти же.
Шаги для воспроизведения:
1. Открыть приложение.
2. Перейти в настройки.
3. Выбрать неправильный файл
4. Нажать кнопку сохранить
5. Приложение вернуло нас на начальный этап не дав возможности исправить файл с этими же настройками
![Снимок экрана 2024-12-24 005537](https://github.com/user-attachments/assets/19f501fc-0791-43d4-82f2-9d76e7e5eca7)
![Снимок экрана 2024-12-24 005544](https://github.com/user-attachments/assets/ec5e92ef-f9bc-4d04-b363-8f505acbb4e5)
![Снимок экрана 2024-12-24 005551](https://github.com/user-attachments/assets/98780468-8c9e-4547-82da-9300aa8a8633)

**Comment by Kolka2** [comment]
[Дубликат](https://github.com/Kolka2/wwms/issues/3).
