### ISSUE TITLE
Некорректная валидация: минимальное количество товара превышает максимальное

### ISSUE THREAD

**Issue by RomanovaKira** [Kolka2/wwms#12]
При открытии приложения заходим в меню настроек и выставляем в пункте "минимальное количество продуктов в заказе" 99(это максимальное число которое дает ввести приложение) и после этого сохраняем настройки. вылезает сообщение об ошибке, однако если мы попробуем ввести 99 продуктов всего то приложение выдаст ошибку.
Шаги для воспроизведения 
1.Открыть приложение.
2. Перейти в настройки
3. в пункте "минимальное количество продуктов в заказе" выставить 99
4. сохранить настройки
![Снимок экрана 2024-12-24 010607](https://github.com/user-attachments/assets/57159a97-5da4-40f3-a8fe-5bfeaaa1b579)
![Снимок экрана 2024-12-24 010621](https://github.com/user-attachments/assets/1c54a628-3635-477e-ade5-542457c32d85)
5. в пункте "количество продуктов всего" выставить 99
![Снимок экрана 2024-12-24 011042](https://github.com/user-attachments/assets/b710b909-5c14-4852-bb82-02e309851de3)
![Снимок экрана 2024-12-24 011046](https://github.com/user-attachments/assets/6f09e7cd-a5b6-4714-9f90-ea4af0d0183a)
Ожидаемое поведение: возможность выбрать больше продуктов либо ограничить минимальное количество

**Comment by Kolka2** [comment]
Всё работает корректно, просто вы не поняли за что отвечают пункты настроек. Об этом уже есть [отдельная тема](https://github.com/Kolka2/wwms/issues/14). Пункты настроек будут переименованы для более точного отображения их смысла.
