### ISSUE TITLE
Неочевидный текст в настройках

### ISSUE THREAD

**Issue by RomanovaKira** [Kolka2/wwms#14]
Оказывается данный файл нужен для записи симуляции в него, а не брать данные из симуляции или чего-нибудь ещё.
Шаги для воспроизведения:
1.Открыть приложение.
2. Нажать кнопку "Настройки"
3. указать файл
4. нажать кнопку сохранить
5. нажать кнопку "Начать симуляцию"
6. открыть файл после этого
7. шокироваться что файл испорчен
Ожидаемое поведение: сохранение данных моего файла, отдельный вывод в другой файл.
![image](https://github.com/user-attachments/assets/f15eed1e-9afd-4fe5-bbb4-4c7d4daf0e92)
![image](https://github.com/user-attachments/assets/2fa7d7c2-84e7-428a-bb7e-4c9583f5624e)
![image](https://github.com/user-attachments/assets/99e56529-19d7-4ffa-9ac9-d99e93560e75)

**Comment by Kolka2** [comment]
[Дубликат](https://github.com/Kolka2/wwms/issues/2). Обсуждение будет вестись там.
