### ISSUE TITLE
(Подпроблема полей)Ошибка в количестве продуктов

### ISSUE THREAD

**Issue by ivan12205** [Kolka2/wwms#4]
Значится вот мы снова в настройках. Интересуют нас 2 поля: "Минимальное количество продуктов в заказе" и "Количество продуктов всего". Логически верно, что минимальное количество не может быть больше общего, но мне дана возможность ввести в первое поле число 99 и никаких примечаний рядом нет. Рядом со вторым полем написано ограничение от 12 до 20. И вот я, как логически тупой, но умеющий читать ввёл 99 в минимум и 20 в общее количество. Сообщение, что так делать нельзя я получил (значит этот момент продуман), но как-то не слишком был ограничен во время ввода. Хотелось бы, чтобы ограничения были не только в виде примечаний рядом с полями, но и чтобы во время ввода нельзя было ввести 21 при ограничении в 0-20 (или каких-либо ещё. Короче динамически блокировать ввод неправильных данных).
1.Открыть приложение.
2.Идём в настройки (не забываем указать нормальный путь)
3.Вводим в "Минимальное количество продуктов в заказе" число больше 20 (ведь никаких примечаний рядом нет, а думать мы не умеем)
4.Вводим в "Количество продуктов всего" число, не нарушающее ограничений (12-20)
5. Ловим как бы неожиданную (ведь мы следовали ограничениям), но вполне логичную ошибку.
![image](https://github.com/user-attachments/assets/591fa221-08c5-42af-bf69-6fb05d70f59a)

**Comment by Kolka2** [comment]
Программа отрабатывает ввод некорректных значений. Динамическая обработка может быть добавлена в будущем.
