### ISSUE TITLE
Некорректный вывод сообщения

### ISSUE THREAD

**Issue by RomanovaKira** [Kolka2/wwms#9]
При открытии настроек в пункте "минимальное количество товара для заказа" мы ввели число 9999999999. В пункте "максимальное количество товара для заказа" мы ввели 9999999999, после чего сохранили настройки, однако приложение утверждает что минимальное число больше чем максимальное. Однако если в эти же поля ввести число 12, то приложение не считает это как ошибку.
Шаги для воспроизведения:
1.Открыть приложение.
2.Перейти в настройки.
3.В пункте "минимальное количество товара для заказа" вписать максимальное число(9999999999)
4. в пункте "максимальное количество товара для заказа" вписать максимальное число(9999999999)
![image](https://github.com/user-attachments/assets/2297622f-7dd4-4b0b-9183-71455c31dc37)
5.В пункте "минимальное количество товара для заказа" вписать 12
6. в пункте "максимальное количество товара для заказа" вписать 12
![Снимок экрана 2024-12-24 005255](https://github.com/user-attachments/assets/e7a78c01-6ad9-4ae2-b219-0aa25378ad29)
Ожидаемое поведение: Приложение должно выдавать одинаковый ответ на одинаковые данные в полях "минимальное количество товара для заказа" и "максимальное количество товара для заказа"

**Comment by Kolka2** [comment]
[Дубликат](https://github.com/Kolka2/wwms/issues/6). Все обсуждения будут вестись там.
